### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by Aiawaska** [HiroshimaTeam/AddNetherite-HiroTeam#2]
When slapping the ground to put armor on the pants go the helmets place

**Comment by HiroshimaTeam** [comment]
This problem does not come from our plugin

**Comment by HiroshimaTeam** [comment]
The problem lies elsewhere

**Comment by ErikPDev** [comment]
That is not true, that's the plugin fault, I tried it with no plugins but only the Netherite plugin. THe error still occurs.
@HiroshimaTeam
