### ISSUE TITLE
Netherite Tools Disapears

### ISSUE THREAD

**Issue by MonoAdrian23** [HiroshimaTeam/AddNetherite-HiroTeam#3]
AddNetherite Dev 4
Pocketmine 3.14.2

Steps to reproduce It

1... Enchant a Netherite Pickaxe
2... Go Farm 10 Minutes
3... The Tool disappears while farming
4... Item ID before Disappears was 755:400

Testet with Efficiency 3 and 4 and Silktouch

Without enchants, it happens to

**Comment by UnEnanoMas** [comment]
x2

**Comment by MonoAdrian23** [comment]
In latest Dev build, it works great.
I Close this issue
